[llvm]
optimize = true
release-debuginfo = false
ccache = "/usr/local/bin/ccache"
ninja = true
#static-libstdcpp = true

#cflags = ""
#cxxflags = ""
#ldflags = ""

[build]

build-stage = 2
test-stage = 2
doc-stage = 2

host = ["armv7-unknown-linux-uclibceabi"]
target = ["armv7-unknown-linux-uclibceabi","mipsel-unknown-linux-uclibc"]

extended = true
cargo-native-static = true

#tools = ["cargo", "clippy", "rustfmt", "analysis", "src"] 

[install]

prefix = "/mmc"
sysconfdir = "etc"

[rust]

optimize = true
debug = false
description = "tomatoware"
rpath = false
channel = "stable"

[target.armv7-unknown-linux-uclibceabi]

cc = "/opt/tomatoware/arm-soft-mmc/bin/arm-linux-gcc"
cxx = "/opt/tomatoware/arm-soft-mmc/bin/arm-linux-g++"
ar = "/opt/tomatoware/arm-soft-mmc/bin/arm-linux-ar"
ranlib = "/opt/tomatoware/arm-soft-mmc/bin/arm-linux-ranlib"
linker = "/opt/tomatoware/arm-soft-mmc/bin/arm-linux-gcc"

[target.mipsel-unknown-linux-uclibc]

cc = "/opt/tomatoware/mipsel-soft-mmc/bin/mipsel-linux-gcc"
cxx = "/opt/tomatoware/mipsel-soft-mmc/bin/mipsel-linux-g++"
ar = "/opt/tomatoware/mipsel-soft-mmc/bin/mipsel-linux-ar"
ranlib = "/opt/tomatoware/mipsel-soft-mmc/bin/mipsel-linux-ranlib"
linker = "/opt/tomatoware/mipsel-soft-mmc/bin/mipsel-linux-gcc"

#crt-static = true

[dist]

src-tarball = false
compression-formats = ["gz"]
